#pragma once

enum {
    NSC_YIELD = 0,
    NSC_SLEEP,
    NSC_CREATE_THREAD,
    NSC_TERMINATE_THREAD,
    NSC_SEND,
    NSC_RECV,
    NSC_REPLY,
    NSC_CALL,
    NSC_NBSEND,
    NSC_NBRECV,
    NSC_NUM_SYSCALLS,
};

#define NSC_HARDFAULT   255